name: PolyHxApp
description: Official PolyHx Mobile App

dependencies:
  shared_preferences:
  intl:
  redux:
  flutter_redux:
  font_awesome_flutter: 6.0.0
  qrcode_reader: ^0.3.2
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/tshirt.png
