name: PolyHxApp
description: Official PolyHx Mobile App

dependencies:
  shared_preferences: ^0.4.2
  intl:
  redux: ^3.0.0
  flutter_redux:
  font_awesome_flutter: ^8.0.1
  qr_reader: ^0.1.3
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.18.1
  redux_epics: ^0.10.0
  flutter_spinkit: ^2.1.0
  qr_flutter: ^1.1.5
  url_launcher: ^4.0.1
  http: ^0.12.0
  crypto: ^2.0.6
  firebase_messaging: ^2.1.0
  google_maps_flutter: ^0.0.3+3
  fluttertoast: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/tshirt.png

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
    - family: Flipbash
      fonts:
        - asset: fonts/Flipbash.otf
